version: '3.8'

services:
  web:
   build: .
   command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
   environment:
    - SECRET_KEY=django-insecure-(g&b^pj32k8)zf3doczyif39v6(gdkcn66)_)nurr5++#46^_*
    - DEBUG=1
    - EMAIL_HOST=smtp.gmail.com
    - EMAIL_HOST_USER=becquerel25@gmail.com
    - EMAIL_HOST_PASSWORD=Geredargamer_1
    - EMAIL_PORT=587
    - EMAIL_USE_TLS=1
    - ENVIRONMENT=development
   volumes:
    - .:/code
   ports:
    - 8000:8000
   depends_on:
    - db
  db:
   image: postgres:11
   volumes:
    - postgres_data:/var/lib/postgresql/data/
   environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
   postgres_data:

