version: '3.8'

services:
  web:
   build: .
   command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
   environment:
    - SECRET_KEY=w1ml7n+5)h0rtqld$%cj1a_(!%pj#(#q$g4@&1z_0&_i8&a@)9
    - DEBUG=0
    - EMAIL_HOST=smtp.gmail.com
    - EMAIL_HOST_USER=becquerel25@gmail.com
    - EMAIL_HOST_PASSWORD=Geredargamer_1
    - EMAIL_PORT=587
    - EMAIL_USE_TLS=1
    - ENVIRONMENT=production
   volumes:
    - .:/code
   ports:
    - 8000:8000
   depends_on:
    - db
  db:
   image: postgres:11
   environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"


